name: Release

on: 
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v4
      with:
        github-token: ${{ secrets.github_token }}
